server:
  port: 10010
spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice #路由的目标地址
          predicates: # 路由断言
            - Path=/user/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: #哪些网站可以跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000

